// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADYnSFTl9kyel4Xj94IaQZetZSbb4cYUg',
    appId: '1:286470675456:web:bc1bdee6e9c9275070cce5',
    messagingSenderId: '286470675456',
    projectId: 'muadk-6e1d5',
    authDomain: 'muadk-6e1d5.firebaseapp.com',
    storageBucket: 'muadk-6e1d5.firebasestorage.app',
    databaseURL: 'https://muadk-6e1d5.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADYnSFTl9kyel4Xj94IaQZetZSbb4cYUg',
    appId: '1:286470675456:android:doctor_web_app_id',
    messagingSenderId: '286470675456',
    projectId: 'muadk-6e1d5',
    storageBucket: 'muadk-6e1d5.firebasestorage.app',
    databaseURL: 'https://muadk-6e1d5.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCnxpw0j9X6ZCNZ0H5UEYbFrAo4tTEca0',
    appId: '1:123456789012:ios:doctor_web_app_ios',
    messagingSenderId: '123456789012',
    projectId: 'muadk-6e1d5',
    storageBucket: 'muadk-6e1d5.appspot.com',
    databaseURL: 'https://muadk-6e1d5.firebaseio.com',
    iosBundleId: 'com.fajr.doctor-web-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCnxpw0j9X6ZCNZ0H5UEYbFrAo4tTEca0',
    appId: '1:123456789012:macos:doctor_web_app_macos',
    messagingSenderId: '123456789012',
    projectId: 'muadk-6e1d5',
    storageBucket: 'muadk-6e1d5.appspot.com',
    databaseURL: 'https://muadk-6e1d5.firebaseio.com',
    iosBundleId: 'com.fajr.doctor-web-app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADYnSFTl9kyel4Xj94IaQZetZSbb4cYUg',
    appId: '1:286470675456:windows:doctor_web_app_windows',
    messagingSenderId: '286470675456',
    projectId: 'muadk-6e1d5',
    storageBucket: 'muadk-6e1d5.firebasestorage.app',
    databaseURL: 'https://muadk-6e1d5.firebaseio.com',
  );
}
